### ISSUE TITLE
Action Logs are not transparent enough

### ISSUE THREAD

**Issue by rumeysakdogan** [Balvajs/dismiss-stale-reviews#110]
Log messages generated by the action are not clear in explaining why the reviews are dismissed. The poor quality of logging leads to confusion and difficulty in diagnosing issues.

**Examples:**
1. In case of a force-push with setting _force-push-action: dismiss-none_, sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-action/pull/4)
Current Log Message:
![Screenshot 2023-10-02 at 10 51 20 AM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/a439e066-c297-4047-8917-f1e05e582c75)
Suggested Log Message: _"force-push-action" is set to "dismiss-none", so no reviews are dismissed._

2. In case of dismissal of reviews when changes introduced related to the same codeowner group, sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-action/pull/9)
Current Log Message:
![Screenshot 2023-10-02 at 12 22 35 PM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/818db647-9bc3-4643-bb64-f4ca9f35d21a)
Suggested Log Message:
```sh
Considering review from <Reviewer_name> from Wednesday 12:00 pm on Commit X
New changes related to <Codeowner Group name that Reviewer belongs to> from Commit X to Commit Y:
Files owned by <Codeowner Group name>:
* <list_of_files_changed>
Reviews to dismiss: < Reviewer_Name>
```

3. Similarly, if changes are not relevant to approved codeowner group,  sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-action/pull/11)
Current Log Message:
![Screenshot 2023-10-02 at 10 51 20 AM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/a439e066-c297-4047-8917-f1e05e582c75)
Suggested Log Message:
```sh
Considering review from <Reviewer_name> from Wednesday 12:00 pm on Commit X
No changes related to <Codeowner Group name that Reviewer belongs to> from Commit X to Commit Y
No reviews to dismiss!
```

4. After rebasing, sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-action/pull/21)
Current Log Message:
![Screenshot 2023-10-02 at 12 02 30 PM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/8bba1f1a-6b68-4019-b853-876aa253eb7e)
Suggested Log Message:
```sh
Commit <commit-sha> doesn't exist in the history. It can be overwritten by force push or outside of checkout depth.
Approval by <Reviewer_name> will be removed.
Reviews to dismiss: <Reviewer_name> 
Files diff can't be resolved for following reviews due to for ce push:
* List of approvers
```
Suggestions for improvements:
* Nice to have an input argument to the action (ACTION_DEBUG: true) so that all of the “thoughts” of the action are printed when diagnosing issues.
* It would be nice to see more details about why a review is not considered or considered to be dismissed to improve transparency of action.

**Comment by Balvajs** [comment]
Hi, thanks for the great report 👏 

I added a log for each review, so it explains which changed files are owned by the review author or their team.
Check out [this PR](https://github.com/Balvajs/dismiss-stale-reviews/pull/116) and let me know if you think it's good enough.
I decided that it won't hurt to have it logged always, so it's not hidden behind the debug flag.

**Comment by rumeysakdogan** [comment]
Thank you for your prompt response! We're very pleased with the current log improvements. Just a small request to improve readability if it is not much to ask. When multiple files are changed from a codeowner group, the files are listed as a long sentence separated with a comma, would it be possible to list them with new lines?
![Screenshot 2023-10-06 at 1 56 57 PM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/2b042bac-164a-4a27-b6b9-f967904bb94c)

After conducting further testing using action from your PR branch, we've identified a few issues that still require attention:
Examples:
1. In case of a force-push(cause: resetting to previous commit, changeset does not have codeowner) with setting force-push-action: dismiss-none, sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-improvements/pull/3)
Force-pushed changes did not cause the dismissal of reviews due to `dismiss-none` setting as expected, but current log message addresses no-owner-action instead of force-push-action setting.

**Current Log Message:**

<img width="838" alt="Screenshot 2023-10-06 at 2 06 19 PM" src="https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/caa88161-343c-4621-92d0-78d912f70f3e">

**Suggested Log Message as Addition to Above:**

```sh
Commit '{commit}' doesn't exist in the history. It may be because it was overwritten by force push or because it's outside of checkout depth.
"force-push-action" is set to "dismiss-none", so no reviews are dismissed.
```

2. UC: Approved reviews are NOT dismissed when new changes are relevant to the codeowner that already approved are force-pushed, force-push-action is set to dismiss-none. Sample execution can be found[ here](https://github.com/test-stuff-123/test-stale-review-improvements/pull/8)
The reason for the reviews being not dismissed is force-push-action setting, but log message saying that changes are not relevant to Codeowner group which is incorrect for this use case.

**Current log Message:**

<img width="894" alt="Screenshot 2023-10-06 at 2 22 17 PM" src="https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/970e2f83-8047-4faf-807c-d850d5d54538">

**Suggested Log Message :**

```sh
Commit '{commit}' doesn't exist in the history. It may be because it was overwritten by force push or because it's outside of checkout depth.
"force-push-action" is set to "dismiss-none", so no reviews are dismissed.
```

3. UC: Updating branch with rebasing option from GitHub GUI should trigger dismissal of reviews. Sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-improvements/pull/17)
Another rebasing scenario, commit history is changed. But approval is not dismissed with below log explanation:

**Current Log Message:** 

<img width="894" alt="Screenshot 2023-10-06 at 2 26 25 PM" src="https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/5eb4e2a6-cf25-49dd-b192-e0af747055a3">

**Suggested Log Message:**

![Screenshot 2023-10-06 at 1 25 59 PM](https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/754d2514-b147-4bef-9d36-9dc507a933de)

**Comment by Balvajs** [comment]
Moved the discussion to #121
