### ISSUE TITLE
Reviews are not dismissed after rebasing

### ISSUE THREAD

**Issue by rumeysakdogan** [Balvajs/dismiss-stale-reviews#117]
Hi, this issue can be considered as a re-opening of #95.

After conducting further tests using action from your PR branch #116, we've identified that no-owner action still takes priority in some use cases:

Examples:
1. UC: Approved reviews are dismissed when changes don’t have a code owner and no-owner-action setting is set to dismiss-none, changes are force-pushed. Sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-improvements/pull/5)
Changes are force-pushed(cause: resetting branch to previous commit), but log message mentions about no-owner-action.

**Current Log message**
 
<img width="894" alt="Screenshot 2023-10-06 at 2 45 14 PM" src="https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/7ee58310-6174-415d-97b3-9498742f5fce">

**Expected Log message**

```sh
Commit '{commit}' doesn't exist in the history. It may be because it was overwritten by force push or because it's outside of checkout depth.
"force-push-action" is set to "dismiss-all", so the following reviews are dismissed...
```

2. UC: Approved reviews are NOT dismissed when changeset without a code owner are force-pushed, both no-owner-action and force-push-action set to dismiss-none. Sample execution can be found [here](https://github.com/test-stuff-123/test-stale-review-improvements/pull/6)

**Current Log message**

<img width="894" alt="Screenshot 2023-10-06 at 2 45 14 PM" src="https://github.com/Balvajs/dismiss-stale-reviews/assets/68822951/ea09f460-c730-41c6-bc02-f23d1c93b891">

**Expected Log message**

```sh
Commit '{commit}' doesn't exist in the history. It may be because it was overwritten by force push or because it's outside of checkout depth.
"force-push-action" is set to "dismiss-all", so the following reviews are dismissed...
```

**Comment by Balvajs** [comment]
Hi, I checked the examples and it seems fine. The force-push didn't affect (alter) the commit that is "approved" (each approval is tied to a specific commit sha). So the action was able to get the changed files without a problem, and it was resolved based on `no-owner-action` config.
Does it make sense to you to have it like this?

**Comment by rumeysakdogan** [comment]
Hi @Balvajs, yes it make sense. I will close the issue now.
