### ISSUE TITLE
Using `Update Branch` button results in incorrect interpretation of force merge

### ISSUE THREAD

**Issue by mikebowyer** [Balvajs/dismiss-stale-reviews#253]
# Description/summary

When a pull request is open with the `dismiss-stale-reviews` action enabled for a workflow, the action will dismiss reviews anytime the `Update Branch` button from GitHub in the browser (as pictured below) when `force-push-action:` is set to `dismiss-all`.

![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/d7965d8f-8d5c-431e-acf4-8da3cc881f25)

This appears to be due to the fact that the `commit_id` returned by a query to the ["List Reviews for a pull request"](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-reviews-for-a-pull-request) will return different values before and after the "Updated Branch" button is selected. Because of this, dismiss-stale-reviews executes and determines that the reviewed SHA and the branch tip SHA are the same, so it must have been a force push. 

# Console logs
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/abcb3a89-cc51-490b-8266-42fc3d6f03fb)

# Visual proof
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/4c3eb9bc-0688-41c9-9c14-1308cd95da8b)

# Steps to reproduce
Set `force-push-action:` to `dismiss-all`, and then simply try to run dismiss-stale-reviews on a triggering event caused by the "Update Branch" button in GitHub.

# Expected result vs. actual result: 

Expected result is that reviews are not dismissed due to merge commit made in the browser, but the actual result is that all reviews are dismissed because they are interpreted as a force push event.

**Comment by mikebowyer** [comment]
@Balvajs, are any further details needed to debug and resolve the issue? Thanks in advance.

**Comment by Balvajs** [comment]
@mikebowyer Thanks for the report 🚀 
You are right, it was broken, I am a bit surprised by how GitHub associates reviews with commits in case of clean merge/rebase. Maybe it changed behavior since I implemented this first time? 🤔 🤷‍♂️ 

Anyway, I stopped treating matching head SHA and review SHA as force-push, and it's now part of https://github.com/Balvajs/dismiss-stale-reviews/releases/tag/v3.0.0 as a breaking change.
