### ISSUE TITLE
Incorrect interpretation of missing commit from history due to shortened commit SHA usage

### ISSUE THREAD

**Issue by mikebowyer** [Balvajs/dismiss-stale-reviews#254]
# Description/summary
When using dismiss-stale-reviews in a larger repository (i.e., one with thousands of commits), there is a failure to find commits by the tool when there are commit SHAs that cannot be resolve by their shortened version alone. 

The end result is that reviews are incorrectly dismissed, as shown below with the reasoning that the reviewed commit was overwritten via a force push.
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/acfbe76c-1931-4319-92fa-fe9037bbe83a)

However, that is simply not that case as the users only merged main via the "Updated Branch" button on GitHub. 
![2023-12-18_09h22_00](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/480ff5f1-3eab-44b5-bcf2-ee64d787b18c)

The problem arises because of the fact that the shortened commit SHA associated with the review is ambiguous as shown in the console logs. However, it is clear that the full commit SHA associated with the commit is available (fetch depth 0 is used).

![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/49719ca1-c83e-480e-a8dc-354a97d54f61)

# Console logs
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/10352611/b7ea946f-6beb-40b5-9cf9-26478ff10e77)

# Visual proof
See above images

# Steps to reproduce

Approve a commit which has the same shortened SHA as another in the repository, set `force-push-action:` `dismiss-all`, trigger dismiss-stale-reviews. 

# Expected result vs. actual result

Expected result is that review commit is able to be checked-out via the full commit SHA. Actual result is a failure to checkout/compare commits that have the same shortened SHA as another in the repository.

**Comment by mikebowyer** [comment]
@Balvajs, are any further details needed to debug and resolve the issue? Thanks in advance.

**Comment by Balvajs** [comment]
@mikebowyer Thanks for the report and thorough writeup 🚀 

It took me some time to get to it, but finally, I managed to find some time and fix your issue. The action is now using only full-length SHAs and the change is part of https://github.com/Balvajs/dismiss-stale-reviews/releases/tag/v2.3.0

Hope it fixes your issue 🤞
