### ISSUE TITLE
Reviews not dismissed on commit after rebase

### ISSUE THREAD

**Issue by agib1** [Balvajs/dismiss-stale-reviews#95]
It’s been noticed that reviews are not dismissed on commit after rebase

Steps taken:
PR created
Approval from codeowner
Local rebase off the main branch with commit which requires a review from codeowner 

Expected result: review dismissed 
Actual result: review wasn’t dismissed 

Arguments set:
no-owner-action - dismiss all
force-push-action - dismiss all 

Thanks

**Comment by Balvajs** [comment]
Hi @agib1, thanks for reporting this 👏 
Can you please share what was the output in the action log? 🙏

**Comment by agib1** [comment]
Hi, 
Thank you for your prompt response. 
For context, we are testing your action to use within a project.

We have an excel document outlining test cases here: 
[Dismiss-Stale-Reviews-Action-Test-Cases.xlsx](https://github.com/Balvajs/dismiss-stale-reviews/files/12768778/Dismiss-Stale-Reviews-Action-Test-Cases.xlsx)

The tests can be found under this repository here: https://github.com/test-stuff-123/test-stale-review-action/pulls

For UC10, we have found flaky behavior. As it is working here but not when previously tested below

Here is our PR with the steps taken and not being dismissed: 
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/60853747/5de2516a-41c7-43a9-8842-a9fcae14bf7a)
And here is the action log output:
![image](https://github.com/Balvajs/dismiss-stale-reviews/assets/60853747/42139a31-237e-4ac3-aa63-3aa3877a8639)

We have observed that the forced push action has priority over no owner action, but there are use cases, refer to UC2.
And in UC4, the no owner action seems to take the priority. 

Thank you

**Comment by Balvajs** [comment]
Thanks for the thorough report 🙇 
I went through it and if I got it right, all the problems are caused by the `no-owner` being resolved before `force-push`, right?
So I just switched the order in https://github.com/Balvajs/dismiss-stale-reviews/pull/115.

I will look at the logging improvements in other PRs.

Let me know if the behavior is still not as expected 🙏
